
namespace WP.SourceGenerators;

/// <summary>
/// Generador de código para registrar automáticamente los Command Handlers, Query Handlers y Validators en el contenedor de dependencias. Este generador analiza las clases que implementan las interfaces ICommandHandler, IQueryHandler o IValidator y genera un método de extensión para IServiceCollection que registra estas implementaciones utilizando AddScoped. Esto facilita la configuración del contenedor de dependencias al eliminar la necesidad de registrar manualmente cada handler o validator, promoviendo una arquitectura más limpia y mantenible en aplicaciones que siguen el patrón CQRS (Command Query Responsibility Segregation).
/// </summary>
[Generator]
public class CqrsRegistrationGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Inicializa el generador de código incremental para registrar automáticamente los Command Handlers, Query Handlers y Validators en el contenedor de dependencias. El generador analiza las clases que implementan las interfaces ICommandHandler, IQueryHandler o IValidator y genera un método de extensión para IServiceCollection que registra estas implementaciones utilizando AddScoped.
    /// </summary>
    /// <param name="context"></param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var implementations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax {BaseList: not null},
                transform: static (ctx, ct) =>
                {
                    ct.ThrowIfCancellationRequested();
                    return GetImplementationInfo(ctx);
                })
            .Where(info => info is not null)
            .Collect();

        context.RegisterSourceOutput(implementations, GenerateSource);
    }

    private static void GenerateSource(SourceProductionContext context, ImmutableArray<(string InterfaceName, string ImplementationName)?> implementations)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// This class is auto-generated by the source generator and should not be modified manually. It registers the generated services into the dependency injection container.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class GeneratedServiceRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// This method is auto-generated by the source generator and should not be modified manually. It registers the generated services into the dependency injection container.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\"></param>");
        sb.AppendLine("    /// <returns></returns>");
        sb.AppendLine("    public static IServiceCollection AddGeneratedServices(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach ((string InterfaceName, string ImplementationName)? info in implementations)
        {
            if (info is null)
            {
                continue;
            }

            sb.AppendLine($"        services.Add(ServiceDescriptor.Scoped(typeof({info.Value.InterfaceName}), typeof({info.Value.ImplementationName})));");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedServiceRegistration.g.cs", sb.ToString());

    }

    private static (string InterfaceName, string ImplementationName)? GetImplementationInfo(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        SemanticModel model = context.SemanticModel;

        if (model.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        foreach (INamedTypeSymbol? interfaceGenrator in classSymbol.AllInterfaces)
        {
            string name = interfaceGenrator.OriginalDefinition.Name;

            if(name is "ICommandHandler" or "IQueryHandler" or "IValidator")
            {
                return (interfaceGenrator.ToDisplayString(), classSymbol.ToDisplayString());
            }
        }
        return null;
    }

}

