<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
      <ProjectReference Include="..\WP.Domain\WP.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WP.SourceGenerators\WP.SourceGenerators.csproj"
                        OutputItemType="Analyzer"
                        ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>
  
</Project>
