@WP_Api_HostAddress = http://localhost:5187

POST {{WP_Api_HostAddress}}/accounts/
Accept: application/json
Content-Type: application/json

{
    "name": "Ahorros",
    "initialAmount": 1000.00,
    "currencyCode": "DOP"
}

###
