@WP_Api_HostAddress = http://localhost:5187

GET {{WP_Api_HostAddress}}/accounts/74c94422-c7d7-4bc5-9070-98c23fecc0a3
Accept: application/json

###

POST {{WP_Api_HostAddress}}/accounts/
Accept: application/json
Content-Type: application/json

{
    "name": "Ahorros",
    "initialAmount": 1000.00,
    "currencyCode": "AAA"
}

###
